- name: Install Node Exporter (Hardcoded Version)
  hosts: node_exporter
  become: yes
  vars:
    # Tentukan versi di sini secara manual
    node_exporter_version: "1.8.2"
    node_exporter_bin: "/usr/local/bin/node_exporter"

  tasks:
    - name: Cek apakah systemd tersedia
      stat:
        path: /run/systemd/system
      register: systemd_check

    - name: Download and Extract Node Exporter
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp
        remote_src: yes
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"

    - name: Copy binary ke /usr/local/bin
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_bin }}"
        mode: "0755"
        remote_src: yes
      notify: Restart node_exporter

    - name: Buat systemd unit file
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=nobody
          ExecStart={{ node_exporter_bin }} --web.listen-address=:9100
          Restart=always

          [Install]
          WantedBy=multi-user.target
      when: systemd_check.stat.exists
      notify:
        - Reload systemd
        - Restart node_exporter

    - name: Pastikan service Node Exporter Running (Systemd)
      systemd:
        name: node_exporter
        state: started
        enabled: yes
      when: systemd_check.stat.exists

    - name: Jalankan Node Exporter manual (Non-Systemd)
      shell: "nohup {{ node_exporter_bin }} --web.listen-address=:9100 > /dev/null 2>&1 &"
      async: 10
      poll: 0
      when: not systemd_check.stat.exists

    - name: Bersihkan sisa file di /tmp
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/node_exporter.tar.gz"
        - "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart node_exporter
      systemd:
        name: node_exporter
        state: restarted
      when: systemd_check.stat.exists
